spring:
  datasource:
    url: jdbc:mysql://${RDS_ENDPOINT}:${RDS_PORT}/mybuddy?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

config:
  domain: ${S3_ENDPOINT}